name: Test pooch download
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual run"
  push:

jobs:
  TestGeokitForGdalVersions:
    name: Test pooch download run number ${{ matrix.run_number }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
        # Min
        os: ["ubuntu-24.04"]
        run_number:
          [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            "20",
          ]
    steps:
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge,nodefaults
          activate-environment: test_env
          conda-remove-defaults: "true"
      - name: Checkout geokit
        uses: actions/checkout@v4
      - name: Install libraries
        shell: pwsh
        id: install-step
        run: |
          ls
          echo "LS Done"
          mamba create -c conda-forge -c nodefaults -n test_env pooch
          echo "Installation done"
          mamba list -n test_env
          echo "libraries printed"
          mamba run -n test_env python get_data_from_zenodo.py
          echo "Import xarray done"
