name: Test pooch download
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual run"
  push:

jobs:
  TestGeokitForGdalVersions:
    name: Test pooch download run number ${{ matrix.run_number }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
        # Min
        os: ["ubuntu-24.04"]
        run_number: [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "17",
            "18",
            "19",
            # "20",
            # "21",
            # "22",
            # "23",
            # "24",
            # "25",
            # "26",
            # "27",
            # "28",
            # "29",
            # "30",
            # "31",
            # "32",
            # "33",
            # "34",
            # "35",
            # "36",
            # "37",
            # "38",
            # "39",
            # "40",
            # "41",
            # "42",
            # "43",
            # "44",
            # "45",
            # "46",
            # "47",
            # "48",
            # "49",
            # "50",
            # "51",
            # "52",
            # "53",
            # "54",
            # "55",
            # "56",
            # "57",
            # "58",
            # "59",
            # "60",
            # "61",
            # "62",
            # "63",
            # "64",
            # "65",
            # "66",
            # "67",
            # "68",
            # "69",
            # "70",
            # "71",
            # "72",
            # "73",
            # "74",
            # "75",
            # "76",
            # "77",
            # "78",
            # "79",
            # "80",
            # "81",
            # "82",
            # "83",
            # "84",
            # "85",
            # "86",
            # "87",
            # "88",
            # "89",
            # "90",
            # "91",
            # "92",
            # "93",
            # "94",
            # "95",
            # "96",
            # "97",
            # "98",
            # "99",
          ]
    steps:
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge,nodefaults
          activate-environment: test_env
          conda-remove-defaults: "true"
      - name: Checkout geokit
        uses: actions/checkout@v4
      - name: Install libraries
        shell: pwsh
        id: install-step
        run: |
          ls
          echo "LS Done"
          mamba create -c conda-forge -c nodefaults -n test_env pooch jupyter nbval pytest pytest-xdist
          echo "Installation done"
          mamba list -n test_env
          echo "libraries printed"
          # mamba run -n test_env python get_data_from_zenodo.py
          # mamba run -n test_env jupyter nbconvert --execute --to notebook get_data_from_zenodo.ipynb
          mamba run --name test_env python -m pytest -vv --dist loadscope --nbval-lax --nbval-current-env --nbval-cell-timeout=900000 --durations=20 examples/
